name: flutter_application_tux
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  pinput: ^2.2.23
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - lib/img/tux.png
      - lib/img/background.png
      - lib/img/notificat.png
      - lib/img/menu.png
      - lib/img/Group 6.png
      - lib/img/Group 7.png
      - lib/img/Group 8.png
      - lib/img/Group 9.png
      - lib/img/Group 10.png
      - lib/img/backicon.png
      - lib/img/file.png
      - lib/img/camera.png
      - lib/img/bear.png
      - lib/img/project.png
      - lib/img/video.png
      - lib/img/attendance.png
      - lib/img/time.png
      - lib/img/tgipoint.png
      - lib/img/Tuitionfee.png
      - lib/img/Elibary.png
      - lib/img/new.png
      - lib/img/internship.png
      - lib/img/drawerpic.png
      - lib/img/line 4.png
      - lib/img/TGipartner.png
      - lib/img/academic.png
      - lib/img/term.png
      - lib/img/call.png
      - lib/img/setting.png
      - lib/img/studentclub.png
      - lib/img/notication.png
      - lib/img/location.png
      - lib/img/cha.jpeg
      - lib/img/search.png
      - lib/img/clear.png
      - lib/img/cardbook.png
      - lib/img/kokkaka.png
      - lib/img/Book1.png
      - lib/img/Book2.png
      - lib/img/Book3.png
      - lib/img/plus.png
      - lib/img/file2.png
      - lib/img/pdf2.png
      - lib/img/pdf.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Montserrat
        fonts:
          - asset: lib/fonts/Montserrat-SemiBold.ttf
         
      - family: Montserrat1
        fonts:
          - asset: lib/fonts/Montserrat-SemiBoldItalic.ttf 
      - family: Niradei
        fonts:
          - asset: lib/fonts/Niradei-Bold-1.otf
      - family: Krasar
        fonts:
          - asset: lib/fonts/Krasar-Regular-2.otf  
      - family: Montserrat2
        fonts:
          - asset: lib/fonts/Montserrat-Medium.ttf  
      - family: Montserrat3
        fonts:
          - asset: lib/fonts/Montserrat-Bold.ttf 
      - family: Montserrat4
        fonts:
          - asset: lib/fonts/Montserrat-Regular.ttf                  

            
   
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
